name: Great learning Actions

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    name: First build
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
            python-version: '3.10'
      - run: pip install blinker
             pip install certifi
             pip install charset-normalizer
             pip install click
             pip install Flask
             pip install idna
             pip install itsdangerous
             pip install Jinja2
             pip install joblib
             pip install numpy
             pip install pandas
             pip install requests
             pip install meson-python
             pip install scikit-learn
             pip install scipy
             pip install threadpoolctl
             pip install urllib3
             
      - uses: mr-smithers-excellent/docker-build-push@v4
        name: Build & push Docker image
        with:
            image: radhikagaba2605/great_learning_model_developement
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            
